[project]
name = "event_planner"
version = "0.1.0"
description = "A simple MAS Event Planner"
authors = [{ name = "mario"}]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[google-genai,tools]==1.14.5a2",
]

[project.scripts]
event_planner = "event_planner.main:run"
run_crew = "event_planner.main:run"
train = "event_planner.main:train"
replay = "event_planner.main:replay"
test = "event_planner.main:test"
run_with_trigger = "event_planner.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"

[tool.uv]
package = true
prerelease = "allow"
