[project]
name = "a"
version = "0.1.0"
description = "a using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.14.5a2"
]

[project.scripts]
a = "a.main:run"
run_crew = "a.main:run"
train = "a.main:train"
replay = "a.main:replay"
test = "a.main:test"
run_with_trigger = "a.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
